### PR TITLE
#1 Login Page is not working(fixed)

### LINKED ISSUE #1: Login Page is not working
# On clicking the google login button it is not working
image
- try to fix that and the design is not responsive
-  need to make design responsive

### PR DESCRIPTION
**Pull request by mohdjami**
[ Closes #1 ] Login Page not Working

Added Authentication and Authorisation using Next-auth Library.

@Aryainguz I have succesfully implemented Login funtionality using Next-auth.
I have used Prisma as an ORM and Supabase for database.
Used 3 providers from next-auth:
- Email Provider
- Github Provider
- Google Provider
Here is the video demonstration.
https://github.com/The-Xiting-Way/DevXClub/assets/114595881/0fae4e65-71a3-45f7-886b-d27adbd3bd9e

New Feature: DARK MODE:
I have also implemented darkmode feature on the navbar using Nextjs inbuilt Next-themes. There will be more work to be done on the UI part for light and dark mode altering tailwind css.

If any changes in UI needed please let me know.

### CODE REVIEW

**Review by MishraTanishq619 — APPROVED** [review]
Yoy did an Outstanding job.

**Comment by mohdjami** [comment]
Thanks @MishraTanishq619, are you willing to work on the UI Part? I can improve it today if you're committing to other issues.

**Review by Latish705 — COMMENTED** [review]
@mohdjami could share video showing working of implementation or feature

**Comment by mohdjami** [comment]
> @mohdjami could share video showing working of implementation or feature

https://github.com/The-Xiting-Way/DevXClub/assets/114595881/0fae4e65-71a3-45f7-886b-d27adbd3bd9e

Here is the video implementation
I can work more on the frontend part as you like.

Also please add level 3 on the issue or any level.

**Review by Latish705 — APPROVED** [review]

**Comment by Aryainguz** [comment]
please @mohdjami fix conflicts

**Comment by mohdjami** [comment]
@Aryainguz Resolved conflicts. 
Before merging please add Level 3 label so that I can gain proper score for this PR.

**Comment by Gurpreet0798** [comment]
Good @mohdjami now your request is merged with the project and also you are assigned the gssoc label.

**Comment by mohdjami** [comment]
> Good @mohdjami now your request is merged with the project and also you are assigned the gssoc label.

Thanks @Gurpreet0798

**Comment by mohdjami** [comment]
Hey @Gurpreet0798 , Please can you label this PR with level3 and assign me this issue because I have not recieved any points from this PR. Kindly label the PR level.

**Pull request merged**
